# Created by Srividhya Chandrasekharn
## Exploratory Data Analysis on Pokemon data set found on Kaggle.

In [1]:
import pandas as pd
import numpy as np

In [135]:
data = pd.read_csv("Pokemon.csv")

In [136]:
data.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [137]:
data.columns = data.columns.str.upper()
data.columns = data.columns.str.replace(" ","")

In [138]:
len(data[data['LEGENDARY']==True])

65

In [139]:
data = data.set_index('NAME')

In [140]:
data.head(3)

#  TYPE1   TYPE2  TOTAL  HP  ATTACK  DEFENSE  SP.ATK  SP.DEF  \
NAME                                                                      
Bulbasaur  1  Grass  Poison    318  45      49       49      65      65   
Ivysaur    2  Grass  Poison    405  60      62       63      80      80   
Venusaur   3  Grass  Poison    525  80      82       83     100     100   

           SPEED  GENERATION  LEGENDARY  
NAME                                     
Bulbasaur     45           1      False  
Ivysaur       60           1      False  
Venusaur      80           1      False

In [141]:
print(data.loc['Bulbasaur']) 

#                  1
TYPE1          Grass
TYPE2         Poison
TOTAL            318
HP                45
ATTACK            49
DEFENSE           49
SP.ATK            65
SP.DEF            65
SPEED             45
GENERATION         1
LEGENDARY      False
Name: Bulbasaur, dtype: object


In [9]:
#Pokemon with the highest total score
data['TOTAL'].idxmax()

'MewtwoMega Mewtwo X'

In [10]:
#Pokemon with the highest HP
data['HP'].argmax()

'Blissey'

In [11]:
#unique pokemon types
data['TYPE1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [12]:
#unique pokemon types
data['TYPE1'].nunique()

18

In [13]:
plot1 = data['TYPE1'].value_counts()

In [14]:
plot2 = data['TYPE2'].value_counts()

In [15]:
plot1

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: TYPE1, dtype: int64

In [16]:
plot2

Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Rock        14
Water       14
Ghost       14
Ice         14
Fire        12
Electric     6
Normal       4
Bug          3
Name: TYPE2, dtype: int64

In [17]:
#pokemon which have only 1 type==> no type2
len(data[data['TYPE2'].isnull()])

386

In [18]:
len(data[data['TYPE2'].isnull()==False]) #pokemon with dual type..

414

In [19]:
data.shape #800 pokemons in total bruh!!

(800, 12)

In [20]:
data['GENERATION'].unique()

array([1, 2, 3, 4, 5, 6])

In [21]:
generation_plot = data['GENERATION'].value_counts()
generation_plot

1    166
5    165
3    160
4    121
2    106
6     82
Name: GENERATION, dtype: int64

In [22]:
sortff= data.sort_values('TOTAL',ascending=False)

In [23]:
sortff.head() #top 5 pokemons decided based on their TOTAL

#    TYPE1     TYPE2  TOTAL   HP  ATTACK  DEFENSE  \
NAME                                                                         
RayquazaMega Rayquaza  384   Dragon    Flying    780  105     180      100   
MewtwoMega Mewtwo Y    150  Psychic       NaN    780  106     150       70   
MewtwoMega Mewtwo X    150  Psychic  Fighting    780  106     190      100   
KyogrePrimal Kyogre    382    Water       NaN    770  100     150       90   
GroudonPrimal Groudon  383   Ground      Fire    770  100     180      160   

                       SP.ATK  SP.DEF  SPEED  GENERATION  LEGENDARY  
NAME                                                                 
RayquazaMega Rayquaza     180     100    115           3       True  
MewtwoMega Mewtwo Y       194     120    140           1       True  
MewtwoMega Mewtwo X       154     100    130           1       True  
KyogrePrimal Kyogre       180     160     90           3       True  
GroudonPrimal Groudon     150      90     90           3       True

In [24]:
import plotly.plotly as py
import plotly.graph_objs as go

In [25]:
#plotly.tools.set_credentials_file(username='your account name', api_key='********')

In [26]:
labels = ['Water', 'Normal', 'Grass','Bug',  'Psychic','Fire', 'Electric', 'Rock', 'Ground','Ghost','Dragon','Dark', 'Poison', 'Fighting', 'Steel','Ice',  'Fairy','Flying']
values = [112, 98, 70, 69, 57, 52, 44, 44, 32, 32, 32, 31, 28, 27, 27, 24, 17,  4]


trace = go.Pie(labels=labels, values=values)
barplot = go.Bar(x=labels, y=values)
py.iplot([trace], filename='basic_pie_chart')


In [27]:
py.iplot([barplot],filename='basic_bar_chart')

In [28]:
data[data['TYPE1']=='Dark']

# TYPE1     TYPE2  TOTAL   HP  ATTACK  DEFENSE  \
NAME                                                                      
Umbreon                197  Dark       NaN    525   95      65      110   
Murkrow                198  Dark    Flying    405   60      85       42   
Sneasel                215  Dark       Ice    430   55      95       55   
Houndour               228  Dark      Fire    330   45      60       30   
Houndoom               229  Dark      Fire    500   75      90       50   
HoundoomMega Houndoom  229  Dark      Fire    600   75      90       90   
Poochyena              261  Dark       NaN    220   35      55       35   
Mightyena              262  Dark       NaN    420   70      90       70   
Sableye                302  Dark     Ghost    380   50      75       75   
SableyeMega Sableye    302  Dark     Ghost    480   50      85      125   
Absol                  359  Dark       NaN    465   65     130       60   
AbsolMega Absol        359  Dark       NaN    565   65     150       60   
Honchkrow              430  Dark    Flying    505  100     125       52   
Weavile                461  Dark       Ice    510   70     120       65   
Darkrai                491  Dark       NaN    600   70      90       90   
Purrloin               509  Dark       NaN    281   41      50       37   
Liepard                510  Dark       NaN    446   64      88       50   
Scraggy                559  Dark  Fighting    348   50      75       70   
Scrafty                560  Dark  Fighting    488   65      90      115   
Zorua                  570  Dark       NaN    330   40      65       40   
Zoroark                571  Dark       NaN    510   60     105       60   
Pawniard               624  Dark     Steel    340   45      85       70   
Bisharp                625  Dark     Steel    490   65     125      100   
Vullaby                629  Dark    Flying    370   70      55       75   
Mandibuzz              630  Dark    Flying    510  110      65      105   
Deino                  633  Dark    Dragon    300   52      65       50   
Zweilous               634  Dark    Dragon    420   72      85       70   
Hydreigon              635  Dark    Dragon    600   92     105       90   
Inkay                  686  Dark   Psychic    288   53      54       53   
Malamar                687  Dark   Psychic    482   86      92       88   
Yveltal                717  Dark    Flying    680  126     131       95   

                       SP.ATK  SP.DEF  SPEED  GENERATION  LEGENDARY  
NAME                                                                 
Umbreon                    60     130     65           2      False  
Murkrow                    85      42     91           2      False  
Sneasel                    35      75    115           2      False  
Houndour                   80      50     65           2      False  
Houndoom                  110      80     95           2      False  
HoundoomMega Houndoom     140      90    115           2      False  
Poochyena                  30      30     35           3      False  
Mightyena                  60      60     70           3      False  
Sableye                    65      65     50           3      False  
SableyeMega Sableye        85     115     20           3      False  
Absol                      75      60     75           3      False  
AbsolMega Absol           115      60    115           3      False  
Honchkrow                 105      52     71           4      False  
Weavile                    45      85    125           4      False  
Darkrai                   135      90    125           4       True  
Purrloin                   50      37     66           5      False  
Liepard                    88      50    106           5      False  
Scraggy                    35      70     48           5      False  
Scrafty                    45     115     58           5      False  
Zorua                      80      40     65           5      False  
Zoroark  

In [29]:
data.sort_values('TOTAL',ascending=False)

#     TYPE1     TYPE2  TOTAL   HP  ATTACK  DEFENSE  \
NAME                                                                            
RayquazaMega Rayquaza    384    Dragon    Flying    780  105     180      100   
MewtwoMega Mewtwo Y      150   Psychic       NaN    780  106     150       70   
MewtwoMega Mewtwo X      150   Psychic  Fighting    780  106     190      100   
KyogrePrimal Kyogre      382     Water       NaN    770  100     150       90   
GroudonPrimal Groudon    383    Ground      Fire    770  100     180      160   
Arceus                   493    Normal       NaN    720  120     120      120   
KyuremWhite Kyurem       646    Dragon       Ice    700  125     120       90   
KyuremBlack Kyurem       646    Dragon       Ice    700  125     170      100   
SalamenceMega Salamence  373    Dragon    Flying    700   95     145      130   
MetagrossMega Metagross  376     Steel   Psychic    700   80     145      150   
LatiasMega Latias        380    Dragon   Psychic    700   80     100      120   
LatiosMega Latios        381    Dragon   Psychic    700   80     130      100   
GarchompMega Garchomp    445    Dragon    Ground    700  108     170      115   
TyranitarMega Tyranitar  248      Rock      Dark    700  100     164      150   
DiancieMega Diancie      719      Rock     Fairy    700   50     160      110   
Rayquaza                 384    Dragon    Flying    680  105     150       90   
GiratinaOrigin Forme     487     Ghost    Dragon    680  150     120      100   
GiratinaAltered Forme    487     Ghost    Dragon    680  150     100      120   
Zekrom                   644    Dragon  Electric    680  100     150      120   
Palkia                   484     Water    Dragon    680   90     120      100   
Dialga                   483     Steel    Dragon    680  100     120      120   
Ho-oh                    250      Fire    Flying    680  106     130       90   
Lugia                    249   Psychic    Flying    680  106      90      130   
Reshiram                 643    Dragon      Fire    680  100     120      100   
Xerneas                  716     Fairy       NaN    680  126     131       95   
HoopaHoopa Unbound       720   Psychic      Dark    680   80     160       60   
Mewtwo                   150   Psychic       NaN    680  106     110       90   
Yveltal                  717      Dark    Flying    680  126     131       95   
Regigigas                486    Normal       NaN    670  110     160      110   
Groudon                  383    Ground       NaN    670  100     150      140   
...                      ...       ...       ...    ...  ...     ...      ...   
Zigzagoon                263    Normal       NaN    240   38      30       41   
Makuhita                 296  Fighting       NaN    237   72      60       30   
Bunnelby                 659    Normal       NaN    237   38      36       38   
Shedinja                 292       Bug     Ghost    236    1      90       45   
Burmy                    412       Bug       NaN    224   40      29       45   
Poochyena                261      Dark       NaN    220   35      55       35   
Lotad                    270     Water     Grass    220   40      30       30   
Seedot                   273     Grass       NaN    220   40      40       50   
Happiny                  440    Normal       NaN    220  100       5        5   
Cleffa                   173     Fairy       NaN    218   50      25       28   
Sentret                  161    Normal       NaN    215   35      46       34   
Spewpa                   665       Bug       NaN    213   45      22       60   
Tyrogue                  236  Fighting       NaN    210   35      35       35   
Igglybuff                174    Normal     Fairy    210   90      30       15   
Wooper                   194     Water    Ground    210   55      45       45   
Silcoon                  266       Bug       NaN    205   50      35       55   
Cascoon                  268       Bug       NaN    205   

In [30]:
strong = data.sort_values('TOTAL',ascending=False).head(10)

In [31]:
strong[strong['LEGENDARY']==True] # Out of the 10 strongest pokemon, 8 are legendary

#    TYPE1     TYPE2  TOTAL   HP  ATTACK  DEFENSE  \
NAME                                                                         
RayquazaMega Rayquaza  384   Dragon    Flying    780  105     180      100   
MewtwoMega Mewtwo Y    150  Psychic       NaN    780  106     150       70   
MewtwoMega Mewtwo X    150  Psychic  Fighting    780  106     190      100   
KyogrePrimal Kyogre    382    Water       NaN    770  100     150       90   
GroudonPrimal Groudon  383   Ground      Fire    770  100     180      160   
Arceus                 493   Normal       NaN    720  120     120      120   
KyuremWhite Kyurem     646   Dragon       Ice    700  125     120       90   
KyuremBlack Kyurem     646   Dragon       Ice    700  125     170      100   

                       SP.ATK  SP.DEF  SPEED  GENERATION  LEGENDARY  
NAME                                                                 
RayquazaMega Rayquaza     180     100    115           3       True  
MewtwoMega Mewtwo Y       194     120    140           1       True  
MewtwoMega Mewtwo X       154     100    130           1       True  
KyogrePrimal Kyogre       180     160     90           3       True  
GroudonPrimal Groudon     150      90     90           3       True  
Arceus                    120     120    120           4       True  
KyuremWhite Kyurem        170     100     95           5       True  
KyuremBlack Kyurem        120      90     95           5       True

In [32]:
#distribution among lengendary pokemon
data[data['LEGENDARY']==True]['TYPE1'].value_counts()

Psychic     14
Dragon      12
Fire         5
Ground       4
Rock         4
Water        4
Steel        4
Electric     4
Grass        3
Dark         2
Ice          2
Flying       2
Normal       2
Ghost        2
Fairy        1
Name: TYPE1, dtype: int64

In [33]:
data[data['LEGENDARY']==True]['TYPE2'].value_counts()

Flying      13
Psychic      5
Dragon       4
Fighting     4
Ice          3
Fire         3
Fairy        2
Ground       1
Water        1
Ghost        1
Dark         1
Electric     1
Steel        1
Name: TYPE2, dtype: int64

In [34]:
legendary = data[data['LEGENDARY']==True]

In [35]:
legendary_single_type = legendary[legendary['TYPE2'].isnull()==True]

In [36]:
legendary_single_type['TYPE1'].value_counts()

Psychic     9
Water       3
Flying      2
Normal      2
Ground      1
Dark        1
Grass       1
Fairy       1
Rock        1
Ice         1
Fire        1
Electric    1
Steel       1
Name: TYPE1, dtype: int64

In [37]:
legendary_single_type.sort_values('TOTAL',ascending=False)

#     TYPE1 TYPE2  TOTAL   HP  ATTACK  DEFENSE  \
NAME                                                                        
MewtwoMega Mewtwo Y      150   Psychic   NaN    780  106     150       70   
KyogrePrimal Kyogre      382     Water   NaN    770  100     150       90   
Arceus                   493    Normal   NaN    720  120     120      120   
Mewtwo                   150   Psychic   NaN    680  106     110       90   
Xerneas                  716     Fairy   NaN    680  126     131       95   
Regigigas                486    Normal   NaN    670  110     160      110   
Kyogre                   382     Water   NaN    670  100     100       90   
Groudon                  383    Ground   NaN    670  100     150      140   
DeoxysAttack Forme       386   Psychic   NaN    600   50     180       20   
DeoxysNormal Forme       386   Psychic   NaN    600   50     150       50   
DeoxysDefense Forme      386   Psychic   NaN    600   50      70      160   
DeoxysSpeed Forme        386   Psychic   NaN    600   50      95       90   
ShayminLand Forme        492     Grass   NaN    600  100     100      100   
Darkrai                  491      Dark   NaN    600   70      90       90   
TornadusTherian Forme    641    Flying   NaN    580   79     100       80   
TornadusIncarnate Forme  641    Flying   NaN    580   79     115       70   
Raikou                   243  Electric   NaN    580   90      85       75   
Regirock                 377      Rock   NaN    580   80     100      200   
Azelf                    482   Psychic   NaN    580   75     125       70   
Mesprit                  481   Psychic   NaN    580   80     105      105   
Regice                   378       Ice   NaN    580   80      50      100   
Entei                    244      Fire   NaN    580  115     115       85   
Suicune                  245     Water   NaN    580  100      75      115   
Registeel                379     Steel   NaN    580   80      75      150   
Uxie                     480   Psychic   NaN    580   75      75      130   

                         SP.ATK  SP.DEF  SPEED  GENERATION  LEGENDARY  
NAME                                                                   
MewtwoMega Mewtwo Y         194     120    140           1       True  
KyogrePrimal Kyogre         180     160     90           3       True  
Arceus                      120     120    120           4       True  
Mewtwo                      154      90    130           1       True  
Xerneas                     131      98     99           6       True  
Regigigas                    80     110    100           4       True  
Kyogre                      150     140     90           3       True  
Groudon                     100      90     90           3       True  
DeoxysAttack Forme          180      20    150           3       True  
DeoxysNormal Forme          150      50    150           3       True  
DeoxysDefense Forme          70     160     90           3       True  
DeoxysSpeed Forme            95      90    180           3       True  
ShayminLand Forme           100     100    100           4       True  
Darkrai                     135      90    125           4       True  
TornadusTherian Forme       110      90    121           5       True  
TornadusIncarnate Forme     125      80    111           5       True  
Raikou                      115     100    115           2       True  
Regirock                     50     100     50           3       True  
Azelf                       125      70    115           4       True  
Mesprit                     105     105     80           4       True  
Regice                      100     200     50           3       True  
Entei                        90      75    100           2       True  
Suicune                      90     115     85           2       True  
Registeel                    75     150     50           3       True  
Uxie                         75     130     95           4       True

## radar chart

In [44]:
import plotly.plotly as py
import plotly.graph_objs as go

dataa = [go.Scatterpolar(
  r = [35, 55, 40, 50, 50, 90,35],
  theta = ['HP','ATTACK','DEFENSE','SP.ATK','SP.DEF','SPEED','HP'],
  fill = 'toself'
)]

layout = go.Layout(
    title="Pikachu abilities",
  polar = dict(
    radialaxis = dict(
      visible = True,
    )
  ),
)

fig = go.Figure(data=dataa, layout=layout)
py.iplot(fig, filename = "pikachu_radar_chart")

In [45]:
data.loc['Pikachu']

#                   25
TYPE1         Electric
TYPE2              NaN
TOTAL              320
HP                  35
ATTACK              55
DEFENSE             40
SP.ATK              50
SP.DEF              50
SPEED               90
GENERATION           1
LEGENDARY        False
Name: Pikachu, dtype: object

In [46]:
data.loc['Charmander']

#                 4
TYPE1          Fire
TYPE2           NaN
TOTAL           309
HP               39
ATTACK           52
DEFENSE          43
SP.ATK           60
SP.DEF           50
SPEED            65
GENERATION        1
LEGENDARY     False
Name: Charmander, dtype: object

In [47]:
dataa = [
    go.Scatterpolar(
      r = [35, 55, 40, 50, 50, 90,35],
      theta = ['HP','ATTACK','DEFENSE','SP.ATK','SP.DEF','SPEED','HP'],
      fill = 'toself',
      name = 'Pikachu'
    ),
    go.Scatterpolar(
      r = [39,52,43,60,50,65,39],
      theta = ['HP','ATTACK','DEFENSE','SP.ATK','SP.DEF','SPEED','HP'],
      fill = 'toself',
      name = 'Charmander'
    )
]

layout = go.Layout(
    title='Pikachu VS Charmander',
  polar = dict(
    radialaxis = dict(
      visible = True,
    )
  ),
  showlegend = True
)

fig = go.Figure(data=dataa, layout=layout)
py.iplot(fig, filename = "radar_pikachuVSCharmander")

## bubble chart

In [53]:
data=temp_data

In [ ]:
labels = ['Water', 'Normal', 'Grass','Bug',  'Psychic','Fire', 'Electric', 'Rock', 'Ground','Ghost','Dragon','Dark', 'Poison', 'Fighting', 'Steel','Ice',  'Fairy','Flying']
values = [112, 98, 70, 69, 57, 52, 44, 44, 32, 32, 32, 31, 28, 27, 27, 24, 17,  4]


In [72]:
trace0 = go.Scatter(
    x=['Water', 'Normal', 'Grass','Bug',  'Psychic','Fire', 'Electric', 'Rock', 'Ground','Ghost','Dragon','Dark', 'Poison', 'Fighting', 'Steel','Ice',  'Fairy','Flying'],
    y=[112, 98, 70, 69, 57, 52, 44, 44, 32, 32, 32, 31, 28, 27, 27, 24, 17,  4],
    mode='markers',
    marker=dict(
        color= 'rgb(122, 65, 244)',
        #color=['rgb(93, 164, 214)', 'rgb(255, 144, 14)',  'rgb(44, 160, 101)', 'rgb(255, 65, 54)','rgb(220, 244, 66)','rgb(122, 65, 244)'],
        size=[112, 98, 70, 69, 57, 52, 44, 44, 32, 32, 32, 31, 28, 27, 27, 24, 17,  4],
    ),
)

py.iplot([trace0], filename='bubblechart-text')

# pie chart showing legendary pokemon types

In [74]:
legendary['TYPE1'].value_counts()

Psychic     14
Dragon      12
Fire         5
Ground       4
Rock         4
Water        4
Steel        4
Electric     4
Grass        3
Dark         2
Ice          2
Flying       2
Normal       2
Ghost        2
Fairy        1
Name: TYPE1, dtype: int64

In [79]:
labels = ['Psychic','Dragon' ,'Fire  ' ,'Ground' ,'Rock  ' ,'Water ' ,'Steel ' ,'Electric','Grass ' ,'Dark  ' ,'Ice   ' ,'Flying' ,'Normal' ,'Ghost ' ,'Fairy ']
values = [14,12, 5, 4, 4, 4, 4, 4, 3, 2, 2, 2, 2, 2, 1]


trace = go.Pie(labels=labels, values=values)
py.iplot([trace], filename='legendary_pokemon_pieChart')

# legendary vs normal 

In [90]:
non_legend = data[data['LEGENDARY']==False]

In [97]:
non_legend['TYPE1'].value_counts()

Water       108
Normal       96
Bug          69
Grass        67
Fire         47
Psychic      43
Rock         40
Electric     40
Ghost        30
Dark         29
Poison       28
Ground       28
Fighting     27
Steel        23
Ice          22
Dragon       20
Fairy        16
Flying        2
Name: TYPE1, dtype: int64

In [170]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff


In [107]:
import plotly
plotly.tools.set_credentials_file(username='csrividhya94', api_key='ox8Clsh4Du2lB5oOXbHU')

In [108]:
trace0 = go.Bar(
   x = ['Psychic','Dragon' ,'Fire  ' ,'Ground' ,'Rock  ' ,'Water ' ,'Steel ' ,'Electric','Grass ' ,'Dark  ' ,'Ice   ' ,'Flying' ,'Normal' ,'Ghost ' ,'Fairy '],
   y = [43,20,47,28,40,108,23,40,67,29,22,2,96,30,16],
    name='Non-legendary pokemon',
    marker=dict(
        color='rgb(49,130,189)'
    )
)
trace1 = go.Bar(
   x = ['Psychic','Dragon' ,'Fire  ' ,'Ground' ,'Rock  ' ,'Water ' ,'Steel ' ,'Electric','Grass ' ,'Dark  ' ,'Ice   ' ,'Flying' ,'Normal' ,'Ghost ' ,'Fairy '],
   y = [14,12, 5, 4, 4, 4, 4, 4, 3, 2, 2, 2, 2, 2, 1],
    name='Legendary',
    marker=dict(
        color='rgb(217, 244, 66)',
    )
)

layout = go.Layout(
    xaxis=dict(tickangle=-45),
    barmode='group',
)

fig = go.Figure(data=[trace0, trace1], layout=layout)
py.iplot(fig, filename='angled-text-bar')

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~csrividhya94/0 or inside your plot.ly account where it is named 'angled-text-bar'


# TABLE with the 2 types

In [149]:
types = np.array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'])
print types[::-1]

['Flying' 'Steel' 'Dark' 'Dragon' 'Ice' 'Ghost' 'Rock' 'Psychic'
 'Fighting' 'Fairy' 'Ground' 'Electric' 'Poison' 'Normal' 'Bug' 'Water'
 'Fire' 'Grass']


In [147]:
ans=[]
count=0
for t1 in types:
    temp=[]
    temp_data = data[data['TYPE1']==t1]
    for t2 in types:
        temp.append(len(temp_data[data['TYPE2']==t2]))
        count=count+len(temp_data[data['TYPE2']==t2])
    ans.append(temp)
print ans

/home/sri/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:7: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

/home/sri/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:8: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.



[[0, 0, 0, 0, 0, 15, 0, 1, 2, 3, 2, 0, 0, 3, 1, 3, 2, 5], [0, 0, 1, 0, 2, 0, 0, 3, 0, 7, 2, 1, 0, 0, 1, 0, 1, 6], [3, 0, 0, 0, 0, 3, 2, 10, 2, 3, 5, 4, 2, 3, 2, 6, 1, 7], [6, 2, 1, 0, 0, 12, 2, 2, 0, 2, 0, 3, 1, 0, 0, 0, 7, 14], [2, 0, 1, 0, 0, 0, 0, 1, 5, 2, 2, 0, 0, 0, 0, 0, 0, 24], [0, 0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 3, 0, 3], [1, 1, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 3, 5], [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 3, 2, 0, 2, 3, 1, 4], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1, 2, 1], [1, 1, 0, 0, 0, 0, 0, 0, 6, 3, 0, 0, 1, 0, 0, 1, 0, 6], [2, 0, 6, 2, 0, 0, 0, 6, 3, 1, 2, 0, 0, 2, 2, 2, 3, 4], [10, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2], [0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 2, 0, 1, 0, 0, 0, 0, 2], [0, 1, 0, 0, 0, 0, 1, 5, 1, 0, 4, 0, 0, 3, 0, 0, 0, 6], [0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 3, 0, 2, 5], [0, 0, 0, 0, 0, 0, 0, 2, 3, 1, 7, 3, 4, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [174]:
counts = np.array([[0, 0, 0, 0, 0, 15, 0, 1, 2, 3, 2, 0, 0, 3, 1, 3, 2, 5], [0, 0, 1, 0, 2, 0, 0, 3, 0, 7, 2, 1, 0, 0, 1, 0, 1, 6], [3, 0, 0, 0, 0, 3, 2, 10, 2, 3, 5, 4, 2, 3, 2, 6, 1, 7], [6, 2, 1, 0, 0, 12, 2, 2, 0, 2, 0, 3, 1, 0, 0, 0, 7, 14], [2, 0, 1, 0, 0, 0, 0, 1, 5, 2, 2, 0, 0, 0, 0, 0, 0, 24], [0, 0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 3, 0, 3], [1, 1, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 3, 5], [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 3, 2, 0, 2, 3, 1, 4], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1, 2, 1], [1, 1, 0, 0, 0, 0, 0, 0, 6, 3, 0, 0, 1, 0, 0, 1, 0, 6], [2, 0, 6, 2, 0, 0, 0, 6, 3, 1, 2, 0, 0, 2, 2, 2, 3, 4], [10, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2], [0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 2, 0, 1, 0, 0, 0, 0, 2], [0, 1, 0, 0, 0, 0, 1, 5, 1, 0, 4, 0, 0, 3, 0, 0, 0, 6], [0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 3, 0, 2, 5], [0, 0, 0, 0, 0, 0, 0, 2, 3, 1, 7, 3, 4, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0]])
z = counts[::-1]
print z

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  2  3  1  7  3  4  0  1  0  0  1]
 [ 0  3  0  0  0  0  0  0  0  2  2  0  2  2  3  0  2  5]
 [ 0  1  0  0  0  0  1  5  1  0  4  0  0  3  0  0  0  6]
 [ 0  0  3  0  0  0  0  3  0  0  2  0  1  0  0  0  0  2]
 [10  3  0  0  0  4  0  0  0  0  0  0  0  0  2  1  0  2]
 [ 2  0  6  2  0  0  0  6  3  1  2  0  0  2  2  2  3  4]
 [ 1  1  0  0  0  0  0  0  6  3  0  0  1  0  0  1  0  6]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  1  2  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  1  0  0  0  0  1  0  0  0  2  3  2  0  2  3  1  4]
 [ 1  1  1  0  2  0  0  0  1  0  0  0  1  1  1  0  3  5]
 [ 0  0  1  1  0  0  0  2  0  2  0  0  0  0  1  3  0  3]
 [ 2  0  1  0  0  0  0  1  5  2  2  0  0  0  0  0  0 24]
 [ 6  2  1  0  0 12  2  2  0  2  0  3  1  0  0  0  7 14]
 [ 3  0  0  0  0  3  2 10  2  3  5  4  2  3  2  6  1  7]
 [ 0  0  1  0  2  0  0  3  0  7  2  1  0  0  1  0  1  6]
 [ 0  0  0  0  0 15  0  1  2  3

In [175]:
z = z

x = ['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying']
y = ['Flying', 'Steel', 'Dark', 'Dragon' ,'Ice' ,'Ghost' ,'Rock' ,'Psychic',
     'Fighting' ,'Fairy' ,'Ground' ,'Electric' ,'Poison', 'Normal' ,'Bug', 'Water',
 'Fire' ,'Grass']


fig = ff.create_annotated_heatmap(z, x=x, y=y, annotation_text=z, colorscale='Viridis')
py.iplot(fig, filename='annotated_heatmap_text')

# subplots with histograms

In [182]:
from plotly import tools
temp_data = data
total = temp_data['TOTAL']
totz = total.tolist()
trace0=go.Histogram(x=totz)

hp=temp_data['HP']
hpz = hp.tolist()
trace1=go.Histogram(x=hpz)

attack=temp_data['ATTACK']
attackz = attack.tolist()
trace2=go.Histogram(x=attackz)

speed=temp_data['SPEED']
speedz = speed.tolist()
trace3=go.Histogram(x=speedz)

defense=temp_data['DEFENSE']
defensez = defense.tolist()
trace4=go.Histogram(x=defensez)

In [185]:
fig = tools.make_subplots(rows=3, cols=2, specs=[[{'colspan': 2}, None],[{}, {}],[{}, {}]],
                          subplot_titles=('Histogram Of Total','Histogram Of HP', 'Histogram Of Attack','Histogram Of Speed', 'Histogram Of Defense'))

fig.append_trace(trace0, 1, 1)
fig.append_trace(trace1, 2, 1)
fig.append_trace(trace2, 2, 2)
fig.append_trace(trace3, 3, 1)
fig.append_trace(trace4, 3, 2)


fig['layout'].update(showlegend=False, title='Histogram Subplots')
py.iplot(fig, filename='custom-sized-subplot-with-subplot-titles')

This is the format of your plot grid:
[ (1,1) x1,y1           -      ]
[ (2,1) x2,y2 ]  [ (2,2) x3,y3 ]
[ (3,1) x4,y4 ]  [ (3,2) x5,y5 ]



# Fight between MewTwo vs MegaRayquaza

In [186]:
data.loc['RayquazaMega Rayquaza']

#                384
TYPE1         Dragon
TYPE2         Flying
TOTAL            780
HP               105
ATTACK           180
DEFENSE          100
SP.ATK           180
SP.DEF           100
SPEED            115
GENERATION         3
LEGENDARY       True
Name: RayquazaMega Rayquaza, dtype: object

In [187]:
data.loc['MewtwoMega Mewtwo X']

#                  150
TYPE1          Psychic
TYPE2         Fighting
TOTAL              780
HP                 106
ATTACK             190
DEFENSE            100
SP.ATK             154
SP.DEF             100
SPEED              130
GENERATION           1
LEGENDARY         True
Name: MewtwoMega Mewtwo X, dtype: object

In [ ]:
[105,180,100,180,100,115]

In [189]:
dataa = [
    go.Scatterpolar(
      r = [105,180,100,180,100,115,105],
      theta = ['HP','ATTACK','DEFENSE','SP.ATK','SP.DEF','SPEED','HP'],
      fill = 'toself',
      name = 'RayquazaMega Rayquaza'
    ),
    go.Scatterpolar(
      r = [106,190,100,154,100,130,106],
      theta = ['HP','ATTACK','DEFENSE','SP.ATK','SP.DEF','SPEED','HP'],
      fill = 'toself',
      name = 'MewtwoMega Mewtwo X'
    )
]

layout = go.Layout(
    title= 'Comparison of the strongest Pokemon',
  polar = dict(
    radialaxis = dict(
      visible = True,
    )
  ),
  showlegend = True
)

fig = go.Figure(data=dataa, layout=layout)
py.iplot(fig, filename = "radar_rayquazaVSmewtwo")

# box plots of all the stats 

In [202]:
HP = data['HP']
SPEED = data['SPEED']
ATTACK = data['ATTACK']
DEFENSE = data['DEFENSE']
SPATTACK = data['SP.ATK']
SPDEFENSE = data['SP.DEF']
TOTAL = data['TOTAL']

In [203]:
hp = HP.tolist()
speed = SPEED.tolist()
attack = ATTACK.tolist()
defense = DEFENSE.tolist()
spattack = SPATTACK.tolist()
spdefense = SPDEFENSE.tolist()
totall = TOTAL.tolist()

In [204]:
trace0 = go.Box(
    y=hp,
    name = 'HP',
)

trace1 = go.Box(
    y=speed,
    name = 'SPEED',
)

trace2 = go.Box(
    y=attack,
    name = 'ATTACK',
)

trace3 = go.Box(
    y=defense,
    name = 'DEFENSE',
)

trace4 = go.Box(
    y=spattack,
    name = 'SPECIAL ATTACK',
)

trace5 = go.Box(
    y=spdefense,
    name = 'SPECIAL DEFENSE',
)

trace6 = go.Box(
    y=totall,
    name = 'TOTAL',
)

py.iplot([trace0, trace1, trace2, trace3, trace4, trace5, trace6],filename = "boxPlot")


# The end!